### ISSUE TITLE
ReXNet_V1-2.0x weight 사용시 문제

### ISSUE THREAD

**Issue by hjlee9182** [clovaai/rexnet#7]
![rexnet](https://user-images.githubusercontent.com/46337218/86903767-c2503b00-c14a-11ea-997d-44201326a7e4.PNG)

위의 코드에서 2.0x weight를 사용시 에러가 발생합니다.

동일한 코드에서 1.0x weight를 사용하였을떄는 문제가 발생하지 않았습니다.

그래서 제 코드가 아닌 다른 부분에서 에러가 있을것으로 예상이 됩니다.

**Comment by dyhan0920** [comment]
@hjlee9182  Thank you for using our pretrained model. There is no error in loading the pretrained model:
![image](https://user-images.githubusercontent.com/31481676/87012031-a78dcd00-c203-11ea-93c2-882885ec77f4.png)

You need to change the code at line 9 to **model=rexnetv1.ReXNetV1(width_mult=2.0)** to  match the model size in order to use ReXNet-2.0x model.

**Comment by hjlee9182** [comment]
Thanks
